org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -Dkotlin.compiler.execution.strategy=in-process

org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableJetifier=true

kotlin.compiler.execution.strategy=in-process

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
